// cli-demo/vue-browser-extension/src/popup/views/About.vue
<template>
  <div class="about">
    <div class="card hero">
      <div class="logo">
        <div class="logo-icon">🚀</div>
      </div>
      <h2>Vue Browser Extension</h2>
      <p class="version">版本 1.0.0</p>
      <p class="description">基于Vue.js构建的现代化浏览器插件开发框架</p>
    </div>
    
    <div class="card">
      <h3 class="card-title">功能特性</h3>
      <ul class="feature-list">
        <li>✅ Vue 3 + Composition API</li>
        <li>✅ Pinia状态管理</li>
        <li>✅ Vue Router路由系统</li>
        <li>✅ 现代化UI界面</li>
        <li>✅ Manifest V3支持</li>
        <li>✅ 热重载开发环境</li>
      </ul>
    </div>
    
    <div class="card">
      <h3 class="card-title">技术栈</h3>
      <div class="tech-stack">
        <span class="tech-item">Vue.js 3</span>
        <span class="tech-item">Vite</span>
        <span class="tech-item">Pinia</span>
        <span class="tech-item">Vue Router</span>
        <span class="tech-item">Chrome Extensions API</span>
      </div>
    </div>
    
    <div class="card">
      <h3 class="card-title">开发信息</h3>
      <div class="info-grid">
        <div class="info-item">
          <strong>构建时间:</strong>
          <span>{{ buildInfo.time }}</span>
        </div>
        <div class="info-item">
          <strong>构建版本:</strong>
          <span>{{ buildInfo.hash }}</span>
        </div>
        <div class="info-item">
          <strong>Node版本:</strong>
          <span>{{ buildInfo.nodeVersion }}</span>
        </div>
      </div>
    </div>
    
    <div class="card">
      <h3 class="card-title">链接</h3>
      <div class="link-buttons">
        <a href="#" class="btn" @click="openGithub">GitHub仓库</a>
        <a href="#" class="btn" @click="openDocs">使用文档</a>
        <a href="#" class="btn" @click="reportIssue">问题反馈</a>
      </div>
    </div>
    
    <div class="card">
      <h3 class="card-title">许可证</h3>
      <p class="license">MIT License © 2024</p>
      <p class="copyright">感谢使用Vue Browser Extension框架！</p>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'

const buildInfo = ref({
  time: new Date().toLocaleString('zh-CN'),
  hash: 'abc123f',
  nodeVersion: '18.17.0'
})

const openGithub = () => {
  chrome.tabs.create({ url: 'https://github.com/your-username/vue-browser-extension' })
}

const openDocs = () => {
  chrome.tabs.create({ url: 'https://your-docs-site.com' })
}

const reportIssue = () => {
  chrome.tabs.create({ url: 'https://github.com/your-username/vue-browser-extension/issues' })
}
</script>

<style scoped>
.about {
  padding: 16px;
}

.hero {
  text-align: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  border: none;
}

.logo {
  margin-bottom: 16px;
}

.logo-icon {
  font-size: 48px;
  line-height: 1;
}

.hero h2 {
  margin: 0 0 8px 0;
  font-size: 20px;
  font-weight: 600;
}

.version {
  margin: 0 0 12px 0;
  font-size: 14px;
  opacity: 0.9;
}

.description {
  margin: 0;
  font-size: 13px;
  opacity: 0.8;
  line-height: 1.4;
}

.feature-list {
  margin: 0;
  padding: 0;
  list-style: none;
}

.feature-list li {
  padding: 4px 0;
  font-size: 13px;
}

.tech-stack {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.tech-item {
  display: inline-block;
  padding: 4px 8px;
  background: #e9ecef;
  border-radius: 12px;
  font-size: 11px;
  color: #495057;
}

.info-grid {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.info-item {
  display: flex;
  justify-content: space-between;
  font-size: 13px;
}

.info-item strong {
  color: #495057;
}

.info-item span {
  color: #6c757d;
  font-family: monospace;
}

.link-buttons {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.link-buttons .btn {
  width: 100%;
  text-align: center;
}

.license, .copyright {
  margin: 0;
  font-size: 13px;
  color: #6c757d;
  text-align: center;
}

.copyright {
  margin-top: 8px;
  font-style: italic;
}
</style>

// cli-demo/react-vite-browser-extension/src/popup/pages/About.tsx
import React from 'react'

interface TechItem {
  name: string
  version?: string
  description?: string
}

interface BuildInfo {
  time: string
  hash: string
  nodeVersion: string
  viteVersion: string
}

const About: React.FC = () => {
  const techStack: TechItem[] = [
    { name: 'React 18', description: '现代化UI框架' },
    { name: 'Vite', description: '极速构建工具' },
    { name: 'TypeScript', description: '类型安全' },
    { name: 'Zustand', description: '状态管理' },
    { name: 'React Router', description: '路由系统' }
  ]

  const features: string[] = [
    '⚛️ React 18 + TypeScript',
    '⚡ Vite超快构建',
    '📊 Zustand状态管理',
    '🌐 React Router路由',
    '🎨 现代化UI设计',
    '🛠 完整开发工具链',
    '📱 响应式界面',
    '🔧 热重载开发'
  ]

  const buildInfo: BuildInfo = {
    time: new Date().toLocaleString('zh-CN'),
    hash: 'abc123f',
    nodeVersion: '18.17.0',
    viteVersion: '5.0.0'
  }

  const openGithub = () => {
    chrome.tabs.create({ 
      url: 'https://github.com/your-username/react-vite-browser-extension' 
    })
  }

  const openDocs = () => {
    chrome.tabs.create({ 
      url: 'https://vitejs.dev/guide/' 
    })
  }

  const reportIssue = () => {
    chrome.tabs.create({ 
      url: 'https://github.com/your-username/react-vite-browser-extension/issues' 
    })
  }

  const openViteDocs = () => {
    chrome.tabs.create({ 
      url: 'https://vitejs.dev/' 
    })
  }

  return (
    <div className="about">
      <div className="card hero">
        <div className="logo">
          <div className="logo-icon">⚡</div>
        </div>
        <h2>React Vite Extension</h2>
        <p className="version">版本 1.0.0</p>
        <p className="description">
          基于React + Vite构建的高性能现代化浏览器插件开发框架
        </p>
      </div>
      
      <div className="card">
        <h3 className="card-title">功能特性</h3>
        <div className="feature-grid">
          {features.map((feature, index) => (
            <div key={index} className="feature-item">
              {feature}
            </div>
          ))}
        </div>
      </div>
      
      <div className="card">
        <h3 className="card-title">技术栈</h3>
        <div className="tech-stack">
          {techStack.map((tech, index) => (
            <div key={index} className="tech-item">
              <span className="tech-name">{tech.name}</span>
              {tech.description && (
                <span className="tech-desc">{tech.description}</span>
              )}
            </div>
          ))}
        </div>
      </div>
      
      <div className="card">
        <h3 className="card-title">构建信息</h3>
        <div className="info-grid">
          <div className="info-item">
            <strong>构建时间:</strong>
            <span>{buildInfo.time}</span>
          </div>
          <div className="info-item">
            <strong>构建版本:</strong>
            <span className="mono">{buildInfo.hash}</span>
          </div>
          <div className="info-item">
            <strong>Node版本:</strong>
            <span className="mono">{buildInfo.nodeVersion}</span>
          </div>
          <div className="info-item">
            <strong>Vite版本:</strong>
            <span className="mono">{buildInfo.viteVersion}</span>
          </div>
        </div>
      </div>
      
      <div className="card">
        <h3 className="card-title">性能优势</h3>
        <div className="performance-list">
          <div className="perf-item">
            <span className="perf-icon">⚡</span>
            <div className="perf-content">
              <strong>极速构建</strong>
              <p>Vite提供毫秒级热重载，开发体验极佳</p>
            </div>
          </div>
          <div className="perf-item">
            <span className="perf-icon">🔧</span>
            <div className="perf-content">
              <strong>开箱即用</strong>
              <p>零配置TypeScript支持，内置优化</p>
            </div>
          </div>
          <div className="perf-item">
            <span className="perf-icon">📦</span>
            <div className="perf-content">
              <strong>现代打包</strong>
              <p>基于Rollup的生产构建，体积更小</p>
            </div>
          </div>
        </div>
      </div>
      
      <div className="card">
        <h3 className="card-title">相关链接</h3>
        <div className="link-buttons">
          <button className="btn" onClick={openGithub}>
            <span>📚</span> GitHub仓库
          </button>
          <button className="btn" onClick={openViteDocs}>
            <span>⚡</span> Vite文档
          </button>
          <button className="btn" onClick={openDocs}>
            <span>📖</span> 使用指南
          </button>
          <button className="btn" onClick={reportIssue}>
            <span>🐛</span> 问题反馈
          </button>
        </div>
      </div>
      
      <div className="card">
        <h3 className="card-title">开源许可</h3>
        <p className="license">MIT License © 2024</p>
        <p className="copyright">
          感谢使用React + Vite浏览器插件开发框架！<br/>
          让我们一起构建更快、更现代的浏览器插件。
        </p>
      </div>
    </div>
  )
}

export default About
